on: [push]

jobs:
  review:
    runs-on: ubuntu-latest
    name: A job to review
    steps:
      - name: Run AI Reviewer
        id: reviewer
        uses: cqrect/ai-reviewer@v0.0.2
        with:
          base-url: https://ark.cn-beijing.volces.com/api/v3
          model-name: ep-20250214142503-7c4q8
          api-key: ${{ secrets.OPENAI_API_KEY }}
      - name: Print AI Answer
        run: echo "AI Answer ${{ steps.reviewer.outputs.answer }}"
