name: AI Code Review

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: AI Reviewer
        uses: cqrect@ai-reviewer@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: 'https://api.openai.com/v1'
          model_name: 'gpt-4'
